### ISSUE TITLE
Cannot open PPI netcdf file

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#10]
Not high priority because it only affects data from one station so far. 
PPI LVL1 files were created sucessfully from KNMI and MeteoSwiss data. I have a problem when reading RMI data. File is found, but cannot be opened properly. Not sure what is happening there. Here's the traceback:

processing 'WindCube-dbs/-vad/-pp' setting!
reading file 'C:\Users\dhara\OneDrive\Documents\customers\PROBE\VMG_2023\data\Skeyes_RMI\2021\202106\20210618\WLS200s-157_2021-06-18_23-57-05_ppi_294_100m.nc'
Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Users\\dhara\\OneDrive\\Documents\\customers\\PROBE\\VMG_2023\\data\\Skeyes_RMI\\2021\\202106\\20210618\\WLS200s-157_2021-06-18_23-57-05_ppi_294_100m.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 81, in main
    proc_dl.dailylvl1()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1739, in dailylvl1
    nc_name= hpl_files.combine_lvl1(hpl_list, confDict, date_chosen)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 148, in combine_lvl1
    ds = xr.concat((hpl_files.read_wc_type(iit) for iit in hpl_list.name)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\concat.py", line 224, in concat
    first_obj, objs = utils.peek_at(objs)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\utils.py", line 196, in peek_at
    peek = next(gen)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 148, in <genexpr>
    ds = xr.concat((hpl_files.read_wc_type(iit) for iit in hpl_list.name)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 272, in read_wc_type
    ds_root = xr.open_dataset(filename)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\api.py", line 495, in open_dataset
    backend_ds = backend.open_dataset(
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 550, in open_dataset
    store = NetCDF4DataStore.open(
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 379, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 327, in __init__
    self.format = self.ds.data_model
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 388, in ds
    return self._acquire()
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 382, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\Users\dhara\anaconda3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src\netCDF4\_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'C:\\Users\\dhara\\OneDrive\\Documents\\customers\\PROBE\\VMG_2023\\data\\Skeyes_RMI\\2021\\202106\\20210618\\WLS200s-157_2021-06-18_23-57-05_ppi_294_100m.nc'

**Comment by jana-p** [comment]
I confirm. The PPI data from different elevations is in separate files, with different scan ID in the file name after "PPI". It might be a good idea to read them separately, when adding this kind of capability in the future. At the moment it takes quite long to process the whole data set.

I'll close this with a mental note for future work.

**Comment by mkay-atm** [comment]
Splitting up the data into different directories works, but it's less user friendly, though the results from the PPIs look good.
![sups_rmi_PPI01_l2_windql_20210618_30min](https://user-images.githubusercontent.com/58219143/222084961-8a2b7c47-90ba-47c8-87fa-caca228f80c8.png)
