### ISSUE TITLE
Variable "time_reference" in input file is not found

### ISSUE THREAD

**Issue by jana-p** [mkay-atm/dl_toolbox#4]
This is not a high priority. I will focus now more on DBS and VAD scans. This issue related to FIXED stare can be fixed later.
The older input files have variable "time_reference" within the Sweep group. In a newer file (different institute, newer lidar model), this variable is outside the Sweep group. That creates the following error when running FIXED stare.

processing 'Windcube-fixed/-stare' setting!
reading file 'C:\Users\dhara\OneDrive\Documents\customers\PROBE\VMG_2023\data\MeteoSwiss\Payerne\2023\202301\20230101\WLS200s-197_2023-01-01_00-01-33_fixed_287_50mTP.nc'
Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 81, in main
    proc_dl.dailylvl1()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1646, in dailylvl1
    nc_name= hpl_files.combine_lvl1(hpl_list, confDict, date_chosen)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 135, in combine_lvl1
    ds = xr.concat((hpl_files.read_wcsradial(iit,confDict) for iit in hpl_list.name)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\concat.py", line 224, in concat
    first_obj, objs = utils.peek_at(objs)
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\utils.py", line 196, in peek_at
    peek = next(gen)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 135, in <genexpr>
    ds = xr.concat((hpl_files.read_wcsradial(iit,confDict) for iit in hpl_list.name)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl_files\hpl_files.py", line 903, in read_wcsradial
    ,{ 'units': "seconds since {}".format(pd.to_datetime(ds_tmp.time_reference.data).strftime('%Y-%m-%d %H:%M:%S'))
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\common.py", line 246, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'time_reference'

**Comment by jana-p** [comment]
This now creates the LVL1 output file. But I get the following error when trying to process LVL2 (which it shouldn't do anyway I guess).

Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 82, in main
    proc_dl.dailylvl2()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 1796, in dailylvl2
    ds_lvl2.attrs['title']= confDict['NC_TITLE']
UnboundLocalError: local variable 'ds_lvl2' referenced before assignment

**Comment by jana-p** [comment]
When I try to plot backscatter, I get this error:

no backscatter data in file, plot CNR instead
Traceback (most recent call last):
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhara\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhara\anaconda3\Scripts\hpl2netCDF-client.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\command_line.py", line 86, in main
    proc_dl.bckql()
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 2071, in bckql
    beta_max, time_mean, range_vec, elevation, vmin, vmax = ql_helper(ds, confDict)
  File "C:\Users\dhara\anaconda3\lib\site-packages\hpl2netCDF_client\hpl2netCDF_client.py", line 568, in ql_helper
    ds['relative_beta'] = ds.cnr
  File "C:\Users\dhara\anaconda3\lib\site-packages\xarray\core\common.py", line 246, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'cnr'

**Comment by mkay-atm** [comment]
Thanks for pointing this out, I created the last problem while dealing with the corrupted netCDF issue. Please check that with this latest fix, no other issues arise. Here is the quicklook output:
![sups_ms_dlidVAD01_l2_anybck_ql_20230101_cycle_max](https://user-images.githubusercontent.com/58219143/222076866-e6eff6fc-d46f-406a-b978-1a2440a230de.png)

**Comment by jana-p** [comment]
Works as expected. Closing this.
